[global]
; pid = /run/php/php8.1-fpm.pid
pid = /run/php8.1-fpm.pid
error_log = /var/log/php8.1-fpm.log
log_level = notice
daemonize  = no

[www]
user = www-data
group = www-data
listen = 0.0.0.0:9010

catch_workers_output = yes
; decorate_workers_output = no

; Allow access to the environment variables that were passed on to Docker
clear_env = no

; Process manager
; pm = dynamic
pm = ondemand

pm.max_children = 5
pm.start_servers = 2
pm.process_idle_timeout = 15s
pm.max_requests = 500
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Health check
ping.path = /php-fpm-ping

; Include other configuration files
; include=/etc/php/7.4/fpm/pool.d/*.conf

php_admin_value[max_execution_time] = 300
