version: '3.8'

services:
  mysql:
    container_name: app_mysql
    image: 'mysql:8.0'
    working_dir: /var/www/html
    volumes:
      - './docker/mysql:/var/lib/mysql'
      - '.:/var/www/html'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=qwerty
    ports:
      - '3306:3306'
    networks:
      - app_network

  nginx:
    container_name: app_nginx
    image: 'nginx:alpine'
    working_dir: /var/www/html
    volumes:
      - '.:/var/www/html'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'
    networks:
      - app_network

  php:
    container_name: app_php
    build:
      context: ./docker/php
    expose:
      - 9000
    volumes:
      - '.:/var/www/html'
    networks:
      - app_network
    depends_on:
      - mysql

networks:
  app_network:
    driver: 'bridge'