user nginx;
worker_processes auto;
pcre_jit on;
pid /var/run/nginx.pid;
# error_log /var/log/nginx/error.log notice
# daemon off;

events {
	worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
        '$status $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';

#    access_log /dev/stdout main;
#    error_log /dev/stdout warn;

    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log notice;
    sendfile on;
    keepalive_timeout 65;
    gzip on;
    gzip_vary on;
    gzip_static on;

    server_tokens off;
    client_max_body_size 50M;
    tcp_nodelay on;


    server {
        listen 80;
        index index.php index.html;
        server_name forms.loc;
        root /var/www/dd/web;
        error_log  /var/log/nginx/forms_error.log;

        # rewrite ^(.+)/+$ $1 permanent;
        location ~ (?<no_slash>.+)/$ {
            return 301 $scheme://$host$no_slash;
        }

        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ \.php$ {
            fastcgi_pass php_forms:9010;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_read_timeout 300;
        }

        location ~ ^/php-fpm-ping$ {
            access_log off;
            allow 127.0.0.1;
            deny all;
            include fastcgi_params;
            fastcgi_read_timeout 300;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass php:9010;
        }



        location ~ ^/favicon.ico$ {
            access_log off;
        }
    }

       server {
               listen 8082;
               index  index.html;
               server_name admin.loc;
               root /var/www/dd/web/vue_front/dist;
               error_log  /var/log/nginx/forms_error.log;

               # rewrite ^(.+)/+$ $1 permanent;
               location ~ (?<no_slash>.+)/$ {
                   return 301 $scheme://$host$no_slash;
               }

               location / {
                   try_files $uri $uri/ /index.html;
               }



           }

}

# Include other configuration files
# include /etc/nginx/conf.d/*.conf;
